### ISSUE TITLE
ChoiceAllLanguageLabels is not a valid JSON

### ISSUE THREAD

**Issue by georged** [GuidoPreite/MetadataCustomAPIs#1]
`ChoiceAllLanguageLabels` as returned `["LanguageCode": 1033, "Label": "NT"]` is not a valid JSON. It should be array of objects, e.g. [ {"LanguageCode": 1033, "Label": "NT"}, {"LanguageCode": 1058, "Label": "Північна територія" } ]. 

![image](https://github.com/GuidoPreite/MetadataCustomAPIs/assets/928254/2bdf35f4-e0c5-4495-a52e-fe9470d93f8e)

**Comment by GuidoPreite** [comment]
fixed with version 1.0.0.1
